version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: build/dev/Dockerfile
    command: sh -c air -c .air.toml
    ports:
      - "1323:8080"
    env_file:
      - .env
    volumes:
      - .:/go/src/github.com/sdn0303/sample-go-echo-api
    depends_on:
      - db
    tty: true

  db:
    image: mariadb:10.5
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
      - "./build/dev/database/initdb.d:/docker-entrypoint-initdb.d"
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=passwd
      - MYSQL_ROOT_PASSWORD=passwd
      - TZ=Asia/Tokyo
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=Asia/Tokyo
    tty: true

  adminer:
    image: adminer
    restart: always
    ports:
      - "18080:8080"

volumes:
  mysql:
    driver: local