// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/sdn0303/sample-go-echo-api/pkg/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
}
